feat: Refactor Google Drive loader for enhanced functionality
pprados/langchain-googledrive pull request #7
Opened 2024-01-17 19:14 UTC by ickma

- Updated the `GoogleDriveUtilities` class in `google_drive.py`
- Made improvements to the loader's functionality and customization options
- Implemented support for different templates for querying the Google Drive API
- Enhanced error handling and logging capabilities for smoother loading and conversion of documents

2024-01-17 19:14 UTC, ickma commented
Preparing PR description...

2024-01-17 19:15 UTC, ickma commented
**[PR Description](https://github.com/pprados/langchain-googledrive/pull/7)** updated to latest commit (https://github.com/pprados/langchain-googledrive/commit/3c0aaa367067f6ba3f5b5d4ebfc4617f5e79d15b)

2024-01-19 07:55 UTC, pprados requested changes

2024-01-19 07:55 UTC, pprados commented on langchain_googledrive/utilities/google_drive.py
> -                except HttpError as e:
it's excessive to capture all the exceptions. Many different reasons can produce an exception (more memory, etc.) You must not hide the cause of these errors.

2024-01-23 17:09 UTC, merged

2024-01-24 02:23 UTC, ickma reviewed
LGTM!